[AOTI] Add missing include to `model.h`
At lest if one tries to compile the AOTI code on Darwin, compilation
fails with implicit instantiation of undefined template error:
```
In file included from /Users/nshulga/git/pytorch/pytorch/torch/include/torch/csrc/inductor/aoti_runtime/arrayref_tensor.h:3:
/Users/nshulga/git/pytorch/pytorch/torch/include/torch/csrc/inductor/aoti_runtime/model.h:69:21: error: implicit instantiation of undefined template 'std::basic_stringstream<char>'
  std::stringstream ss;
```

ghstack-source-id: a31dd37e62c926aa73ce046e91dadf03634757a1
Pull Request resolved: https://github.com/pytorch/pytorch/pull/118075